### ISSUE TITLE
In a big dataset that has about 1400 cells the "plotSilhouette" function is not generating any plot.

### ISSUE THREAD

**Issue by SystemsBiologist** [ocbe-uio/DIscBIO#19]
# Describe the bug

# Steps to Reproduce

Try to create a minimally-reproducible example so other people can better understand the problem.

4. Reproduce the following code:
```

```

# Expected behavior

# Screenshots

# Software metainformation
 - Operating System and version: [e.g. Linux, Mac, Windows]
 - R version:
 - DIscBIO version or commit number:

# Additional context

**Comment by wleoncio** [comment]
Is there a link to download the dataset? Could you please add that plus a short script that reproduces the issue to the "Steps to Reproduce" section on the original post?

**Comment by SystemsBiologist** [comment]
I fixed this issue

**Comment by wleoncio** [comment]
> I fixed this issue

Fantastic, ~I'll close the issue, then~. If you can find the commit hash that fixes the issue (e.g., 75beb4b4efa22ebc4c74899c3d54201cbf2a5754), please paste it here so we can keep track.

edit: sorry, just noticed the issue has been closed for almost 2 weeks now. Blame it on my baby-brain. :baby: :brain:
