### ISSUE TITLE
ClustDiffGenes is generating opposite tables

### ISSUE THREAD

**Issue by SystemsBiologist** [ocbe-uio/DIscBIO#20]
# Expected behavior
The up should be down and the down should be up

# Additional context
This is most likely due the ">" in line 122.

**Comment by wleoncio** [comment]
Should it be changed to `<` or `<=`?

**Comment by SystemsBiologist** [comment]
I think "<" is better

**Comment by wleoncio** [comment]
Supposedly fixed on commit https://github.com/ocbe-uio/DIscBIO/commit/8539f14bde6bce14fd9d02a4934e90e91469d79b. Please reopen issue if it doesn't.
