### ISSUE TITLE
The PPI function is writing to the user's disk

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/DIscBIO#33]
# Summary
The following lines of `PPI()` always write and read a file from the user's local drive:

https://github.com/ocbe-uio/DIscBIO/blob/5b2b23aa5b5dd1440e4982dd6c2435dcfabfdf55/R/PPI.R#L42-L45

# DIscBIO version
1.1.0

# Expected output
R functions are not supposed to write on the user's working directory unless explicitly told to.

**Comment by wleoncio** [comment]
This issue was discovered while handling issue #29. A fix should be issued ASAP.

**Comment by wleoncio** [comment]
@SystemsBiologist, `repo_content` is a 3D array with the following lengths:

```r
> dim(repo_content)
[1] 5627 5449    4
```

When saving the results as a CSV file, only the first 5627x5449 matrix is saved (that's the default behavior of `write.csv`). Why are the other 3 discarded?

**Comment by SystemsBiologist** [comment]
Because we are only interested in the PPI data

**Comment by wleoncio** [comment]
Got it. We still need to replace the writing/reading with something that internally handles this, though. I imagine `results <- data.frame(repo_content[, , 1])` will suffice. ~~I'll issue a PR with that for you to review~~. Sorry, I had a brain fart and ended up commiting to dev straight up and forgot the PR. @SystemsBiologist, please check out the changes made on commit e2915183d094593bd51913ee7bee3d4159da99bc and let me know if they are OK.
